#!/bin/bash

# Load resources

xrdb -merge .Xresources

# Set up an icon tray
#trayer --edge top --align right --SetDockType true --SetPartialStrut true \
# --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# Set the background color<
feh --bg-fill /home/tippenein/pics/3d_water_wallpapers-normal.jpg

setxkbmap -option caps:escape

xscreensaver -no-splash &

firefox &
urxvt &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/xfce4-power-manager ] ; then
   sleep 3
   xfce4-power-manager &
fi

exec xmonad
